# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM oven/bun:latest

# Create app directory
WORKDIR /app

# Copy package.json, bun.lock, tsconfig, etc.
COPY package.json bun.lock tsconfig.json ./

# Copy source code
COPY index.ts ./
COPY lib ./lib
COPY tools ./tools
COPY types ./types

# Install dependencies using Bun
RUN bun install

# Expose port if needed (not required for stdio based MCP)

# CMD will be provided by the startCommand; fallback command:
CMD ["bun", "run", "index.ts", "--apiKey=dummy"]
